name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

runs:
  using: 'node20'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install

      - name: SSH to DigitalOcean and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh nodejs@localhost << 'EOF'
            cd /var/www/html
            git pull origin main
            npm ci
            pm2 restart bot
            chown -R nodejs:nodejs /var/www/html
            EOF
